### ISSUE TITLE
ECL_HAS_EXCEPTIONS is false in release mode

### ISSUE THREAD

**Issue by stonier** [stonier/ecl_core#6]
This is rather unintuitive, I should perhaps define this as ECL_HAS_DEBUG_EXCEPTIONS, and further define this differently.

**Comment by pallegro** [comment]
This is causing a build failure for me because in ecl_ipc/src/lib/shared_memory_pos.cpp openSharedSectionException and memoryMapException aren't defined due to ECL_HAS_EXCEPTIONS being false and they're used inside a ecl_throw rather than ecl_debug_throw (which seems to be used elsewhere for these).

What would you recommend: 1) replacing #ifdef ECL_HAS_EXCEPTIONS with #ifndef ECL_DISABLE_EXCEPTIONS so openSharedSectionException and memoryMapException get define, 2) replacing those two ecl_throw's with ecl_debug_throw's or, 3) making sure ECL_HAS_EXCEPTIONS is defined for all of ecl_core ?

Cheers

**Comment by stonier** [comment]
In america at the moment and I should get my head into this before I answer, so I'll have a poke on the weekend. Thanks for the heads up.

**Comment by stonier** [comment]
I have no problems in release mode. By chance was the fix that you're looking for put in 7246843e60b259be7400a07c49446b8f9c3cbc4d? If you have the latest source, or version 0.50.3, it should be fixed.

**Comment by pallegro** [comment]
Ahh, sorry, I was running 0.44.0 from trunk of https://code.google.com/p/embedded-control-library.
FYI this is what is given at http://www.ros.org/wiki/ecl_core (and ecl_tools, ecl_litem, ecl_manipulation , ecl_navigation) and by roslocate.

**Comment by stonier** [comment]
Ah, looks like the documentation isn't getting generated since Nov 22.

I'll open a separate issue for that. Thanks for the heads up.

**Comment by stonier** [comment]
Following up in https://github.com/stonier/ecl_core/issues/8.

Was incorrectly trying to find doc repos at svn, not git.
